projects:
  GraphqlAPI:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: ap-northeast-1
        apiId: kfbhd25t35eqrfypeyyfjjtozq
        maxDepth: 2
